{
 "title": "PlantineraNew Fa",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM \"medicionesCO2\" WITH KEY = \"device\""
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "SHOW TAG VALUES FROM \"medicionesCO2\" WITH KEY = \"sensor\""
   }
  ]
 },
 "panels": [
  { "title": "Overview - Current Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "query": "SELECT last(\"temp\") FROM \"medicionesCO2\" WHERE (\"device\" =~ /^$device$/ AND \"sensor\" =~ /^$sensor$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "hum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "pH Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "ph" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Promedio Soil Moisture",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "query": "SELECT mean(\"moisture\") FROM \"medicionesCO2\" WHERE (\"device\" =~ /^$device$/ AND \"sensor\" =~ /^$sensor$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "soilHum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  { "title": "Environmental Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_device $tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "query": "SELECT mean(\"temp\") FROM \"medicionesCO2\" WHERE (\"device\" =~ /^$device$/ AND \"sensor\" =~ /^$sensor$/) AND \"temp\" <100 AND $timeFilter GROUP BY time($__interval), \"sensor\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Ambient Humidity History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_device $tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "query": "SELECT mean(\"hum\") FROM \"medicionesCO2\" WHERE (\"device\" =~ /^$device$/ AND \"sensor\" =~ /^$sensor$/) AND \"hum\"<110 AND $timeFilter GROUP BY time($__interval), \"sensor\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "hum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "pH Level History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "alias": "$tag_device $tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "ph" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_device $tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "soilHum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "$tag_device $tag_sensor (moisture)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "moisture" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  { "title": "Soil Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Electrical Conductivity (EC) History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_device $tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "ec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "NPK Current Levels (mg/kg)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Nitrogen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "nitrogen" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "Phosphorus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "phosphorus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "Potassium",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "potassium" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "NPK History (mg/kg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_device Nitrogen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "nitrogen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "$tag_device Phosphorus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "phosphorus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "$tag_device Potassium",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "medicionesCO2",
     "select": [
      [
       { "params": [ "potassium" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Relay Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relay 1 Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Relay 1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "relay1" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Relay 2 Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Relay 2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "relay2" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Input 1 Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Input 1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "in1" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Input 2 Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Input 2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "in2" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Relay State Timeline",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Relay 1",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "relay1" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      },
      {
       "alias": "Relay 2",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "relay2" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Input State Timeline",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Input 1",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "in1" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      },
      {
       "alias": "Input 2",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "medicionesCO2",
       "select": [
        [
         { "params": [ "in2" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}