name: Build Firmware

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Add Arduino CLI to PATH
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      
    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "$HOME/bin" >> $GITHUB_PATH  

    - name: Configure Arduino CLI
      run: |
        arduino-cli config init
        arduino-cli config set board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install Required Libraries
      run: |
        arduino-cli lib install "HTTPClient"
        arduino-cli lib install "Adafruit SCD30"

    - name: Build Firmware
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src/embedded/test/SendToGrafana/SendToGrafana.ino

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "binarios/*"
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: "Binarios de firmware generados automáticamente"
        token: ${{ secrets.GITHUB_TOKEN }}
